struct VertexInput {
    float2 position;
    float3 color;
};

struct VertexOutput {
    float4 sv_position : SV_position;
    float3 color;
};

[shader("vertex")]
VertexOutput vertMain(VertexInput input) {
    VertexOutput output;
    output.sv_position = float4(input.position, 0.0, 1.0);
    output.color = input.color;

    return output;
}

[shader("fragment")]
float4 fragMain(VertexOutput input) : SV_Target {
    float4 output = float4(input.color, 1.0);

    return output;
}
